// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WeChatCorp_AllowUserBind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WeChatCorp_AllowUserBind));
        
        string IMigrationMetadata.Id
        {
            get { return "201806060641298_WeChatCorp_AllowUserBind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
